name: it4gaz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  fl_chart: ^0.70.2
  flutter_bloc: ^9.0.0
  logger: ^2.5.0
  intl: ^0.18.0
  flutter_gen: ^5.9.0
  vph_web_date_picker: ^0.1.3
  get_it: ^7.2.0
  pressable: ^0.7.0
  fl_chart: ^0.70.2
  masked_text: ^1.1.2
  intl: ^0.18.1
  vph_web_date_picker: ^0.0.6
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0

flutter_gen:
  output: lib/gen/ 

  integrations:
    image: true
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    - assets/logo/it4gaz_logo.jpg
    - assets/icons/clock.png
    - assets/icons/warning_icon.png
    - assets/icons/box_icon.png
    - assets/icons/diog_icon.png
    - assets/icons/graph_icon.png
    - assets/icons/tab_icon.png
    - assets/icons/home_icon.png

